### ISSUE TITLE
update README with instructions for terraform 0.14

### ISSUE THREAD

**Issue by OriHoch** [Kamatera/terraform-provider-kamatera#10]
* specify in README that minimal supported version is 0.14
* update the instructions for 0.14 (I think current instructions will not work)

**Comment by imcvampire** [comment]
Let me check again, but our plugin still supports <0.14, only our tests need to gen code that supports the used version - 0.14.

**Comment by OriHoch** [comment]
so currently a user with terraform 0.14 can use the provider according to README?

**Comment by OriHoch** [comment]
also, no reason to support older versions at this point, provider is still not widely used and we will make many changes to it, best to support just latest version

**Comment by imcvampire** [comment]
0.13 only has a change in the terraform tf syntax and doesn't require any change in our code. Even we don't aim to support older versions, our provider will still work with older terraform at this point.
