### ISSUE TITLE
disk operations 

### ISSUE THREAD

**Issue by imcvampire** [Kamatera/terraform-provider-kamatera#12]
There are some operations that we could add to the provider:

- [x] Add disk(s)
- [x] Resize disk(s)
- [x] Remove disk(s)

There are some edge/corner cases that we need to take care: 
- [x] The main disk can't be removed.  
- [ ] If there is a snapshot for a disk, raise an error to ask users to delete by themself.

How we do:
- Load the latest state (if there is any) [1]
- Find needed steps and draw a plan 
- Execute 

Config:
```
data "kamatera_server_options" "B1_1024_monthly" {
    ...
    disks = ["10GB", "20GB"]
}
```

[1] https://www.terraform.io/docs/language/state/index.html

**Comment by OriHoch** [comment]
thanks, would be good to see an example terraform config which includes this data

**Comment by imcvampire** [comment]
@OriHoch Terraform config could be:

```
    data "kamatera_server_options" "B1_1024_monthly" {
      ...
      disks = ["10GB", "20GB"]
    }
```

**Comment by OriHoch** [comment]
the first option of a list of disks seems fine, from end-user perspective there is no distinction between main and secondary disks

**Comment by OriHoch** [comment]
regarding snapshots - I don't think it's a good idea to just remove a snapshot, that might not be what the end-user expects and might cause loss of data

**Comment by imcvampire** [comment]
Because the user can't remove the main/first disk, so we need to note it if we choose the first config. 

For the snapshot, so we can throw an error, and provide another config to manage the snapshot?

**Comment by OriHoch** [comment]
yes, so if the disks list is empty you can raise an error

regarding snapshots - for first stage you can just not allow to delete or resize a disk which has a snapshot and ask user to delete the snapshot manually

**Comment by imcvampire** [comment]
Okay. I will update the description.
