### ISSUE TITLE
error terminating server (Failed 3)

### ISSUE THREAD

**Issue by OriHoch** [Kamatera/terraform-provider-kamatera#19]
**Reproduction Steps**

* Perform the following operations very quickly one after the other (see the timestamps for the delay between tasks):
![image](https://user-images.githubusercontent.com/1198854/119855836-ef503c80-bf1a-11eb-99bf-ca10ce3f6db6.png)

**expected**

should terminate the server

**actual**

final operation of terminating the server fails with the error `Failed 3`:

![image](https://user-images.githubusercontent.com/1198854/119856193-350d0500-bf1b-11eb-97f8-174d068ffd8b.png)

**Comment by imcvampire** [comment]
Do multiple operations during a short time can cause this problem? I will add some `sleep` in the test case for checking

**Comment by imcvampire** [comment]
Seems the `sleep(2)` solution works

**Comment by OriHoch** [comment]
great, you should focus more on unit tests

**Comment by imcvampire** [comment]
Even with `sleep(2)`, this problem is still happening.

**Comment by OriHoch** [comment]
I sent to Kamatera, but please focus on unit tests, we will handle integration tests in kamateratoolbox, foe example - https://github.com/Kamatera/kamateratoolbox/blob/master/tests/cloudcli_server/test_server_disk.py

**Comment by imcvampire** [comment]
Okay, it's quite annoying because I can't merge my MR :-( In the meantime, I will focus on unit test.

**Comment by OriHoch** [comment]
please don't merge the disk operations PR because I want to see unit tests with it

but generally you can merge if integration tests didn't pass due to this problem
