### ISSUE TITLE
How do I reference a private image in main.tf ? 

### ISSUE THREAD

**Issue by integrateddigital** [Kamatera/terraform-provider-kamatera#27]
Cannot find any example, would like to use a private image,
but when doing
#Custom Image Middleware
data "kamatera_image" "IMAGE_NAME" {

  datacenter_id = data.kamatera_datacenter.toronto.id
  
}

it does not find the image ... thanks in advance for any help,
s

**Comment by OriHoch** [comment]
Hi, thanks a lot for this bug report

I added a section explaining how you can use private images: https://github.com/Kamatera/terraform-provider-kamatera/blob/master/README.md#using-a-private-image

**Comment by integrateddigital** [comment]
Thanks. I wish kamatera support would not have told us that they do not
support it ... thanks for your help, nothing personal.
