### ISSUE TITLE
make adjustments to support Terraform 0.14

### ISSUE THREAD

**Issue by OriHoch** [Kamatera/terraform-provider-kamatera#7]
We can specify that minimal supported Terraform version is 0.14

**Comment by tomjohnburton** [comment]
It seems this repo has gone quiet. I have forked it and will be happy to review PRs

https://github.com/tomjohnburton/terraform-provider-kamatera

**Comment by OriHoch** [comment]
thanks a lot, @imcvampire is starting to work on it now

**Comment by imcvampire** [comment]
@tomjohnburton I have a PR but haven't fixed errors caused by the new version from Terraform

**Comment by tomjohnburton** [comment]
Sorry I only just realised you are a maintainer 😂. Sounds good!

Kind regards,



Tom

**Comment by imcvampire** [comment]
@tomjohnburton Please free to contribute, man. Every contribution is welcome.
